### ISSUE TITLE
Cannot find encoder

### ISSUE THREAD

**Issue by mpergament** [mre/kafka-influxdb#30] opened 2016-03-18 13:58 UTC
root@c358466be7e1:/home/kafka-influxdb# /usr/local/bin/kafka_influxdb -c config.yaml 
Reading config file config.yaml
Traceback (most recent call last):
  File "/usr/local/bin/kafka_influxdb", line 9, in <module>
    load_entry_point('kafka-influxdb==0.7.2', 'console_scripts', 'kafka_influxdb')()
  File "/usr/local/lib/python2.7/dist-packages/kafka_influxdb/kafka_influxdb.py", line 102, in main
    start_consumer(config)
  File "/usr/local/lib/python2.7/dist-packages/kafka_influxdb/kafka_influxdb.py", line 118, in start_consumer
    encoder = load_encoder(config.encoder)
  File "/usr/local/lib/python2.7/dist-packages/kafka_influxdb/encoder/__init__.py", line 9, in load_encoder
    encoder_module = importlib.import_module(modname)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named kafka_influxdb.encoder.collectd_json_encoder
root@c358466be7e1:/home/kafka-influxdb# find / -name collectd_json_encoder*                                         
/usr/local/lib/python2.7/dist-packages/kafka_influxdb/encoder/collectd_json_encoder.py
/usr/local/lib/python2.7/dist-packages/kafka_influxdb/encoder/collectd_json_encoder.pyc

**Comment by ship1999** [comment] 2016-05-21 03:01
may be you replace  "kafka_influxdb.encoder.collectd_json_encoder" to "collectd_json_encoder" of config.yaml, and try again.

**Comment by mre** [comment] 2016-05-30 11:38
@mpergament, the idea from @ship1999 seems to be working (see #32).
You could try and maybe give some feedback if you find the time.
Will close this for now. Please feel free to reopen if the problem is not fixed by this.

@mpergament thanks for opening the issue :+1: 
@ship1999 thanks for providing a possible fix. Highly appreciate that. :cocktail:

**Closed by mre** 2016-05-30 11:38 UTC
